# Generated by Django 2.2 on 2019-04-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='condition',
            field=models.CharField(max_length=2, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='edition',
            field=models.CharField(max_length=64, null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='location',
            field=models.CharField(max_length=128, null=True, verbose_name='Position where stored'),
        ),
    ]
