# Generated by Django 2.2 on 2019-04-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_auto_20190422_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='condition',
            field=models.CharField(blank=True, max_length=2, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='edition',
            field=models.CharField(blank=True, max_length=64, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='location',
            field=models.CharField(blank=True, max_length=128, verbose_name='Position where stored'),
        ),
    ]
