# Generated by Django 2.2 on 2019-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_auto_20190518_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='foil',
            field=models.BooleanField(default=False, null=True, verbose_name='Foil'),
        ),
    ]
