# Generated by Django 2.2 on 2019-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0005_auto_20190518_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='value',
            field=models.FloatField(default=0.0, null=True, verbose_name='Value quantity value'),
        ),
    ]
