# Generated by Django 2.2 on 2019-05-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_auto_20190518_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Value'),
        ),
    ]
