# Generated by Django 2.2 on 2019-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_auto_20190523_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='id',
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, verbose_name='Card Name'),
        ),
    ]
