# Generated by Django 2.2 on 2019-06-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0008_auto_20190530_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
