# Generated by Django 2.2 on 2019-06-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0009_auto_20190622_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Card Name'),
        ),
    ]
