# Generated by Django 2.2 on 2019-06-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0011_auto_20190626_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='set',
            new_name='expansion',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'expansion', 'condition', 'foil')},
        ),
    ]
