# Generated by Django 2.2 on 2019-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0012_auto_20190626_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expansion',
            field=models.CharField(blank=True, max_length=64, verbose_name='Expansion'),
        ),
    ]
