
GOOD_RESPONSE = {"object": "card",
                 "id": "6b3a20ac-1860-4513-bb73-35d23b088b04",
                 "oracle_id": "de2440de-e948-4811-903c-0bbe376ff64d",
                 "multiverse_ids": [397719],
                 "mtgo_id": 57258,
                 "mtgo_foil_id": 57259,
                 "tcgplayer_id": 98395,
                 "name": "Mox Opal",
                 "lang": "en",
                 "released_at": "2015-05-22",
                 "uri": "https://api.scryfall.com/cards/6b3a20ac-1860-4513-bb73-35d23b088b04",
                 "scryfall_uri": "https://scryfall.com/card/mm2/223/mox-opal?utm_source=api",
                 "layout": "normal",
                 "highres_image":  True,
                 "image_uris": {"small": "https://img.scryfall.com/cards/small/en/mm2/223.jpg?1517813031",
                 "normal": "https://img.scryfall.com/cards/normal/en/mm2/223.jpg?1517813031",
                 "large": "https://img.scryfall.com/cards/large/en/mm2/223.jpg?1517813031",
                 "png": "https://img.scryfall.com/cards/png/en/mm2/223.png?1517813031",
                 "art_crop": "https://img.scryfall.com/cards/art_crop/en/mm2/223.jpg?1517813031",
                 "border_crop": "https://img.scryfall.com/cards/border_crop/en/mm2/223.jpg?1517813031"},
                 "mana_cost": "{0}",
                 "cmc": 0.0,
                 "type_line": "Legendary Artifact",
                 "oracle_text": "Metalcraft — {T}: Add one mana of any color. Activate this ability only if you control three or more artifacts.",
                 "colors": [],
                 "color_identity": [],
                 "legalities": {"standard": "not_legal",
                 "future": "not_legal",
                 "frontier": "not_legal",
                 "modern": "legal",
                 "legacy": "legal",
                 "pauper": "not_legal",
                 "vintage": "legal",
                 "penny": "not_legal",
                 "commander": "legal",
                 "duel": "legal",
                 "oldschool": "not_legal"},
                 "games": ["mtgo",
                 "paper"],
                 "reserved": False,
                 "foil": True,
                 "nonfoil": True,
                 "oversized": False,
                 "promo": False,
                 "reprint": True,
                 "variation": False,
                 "set": "mm2",
                 "set_name": "Modern Masters 2015",
                 "set_type": "masters",
                 "set_uri": "https://api.scryfall.com/sets/28cac015-43df-4e88-90d0-95dcdd894834",
                 "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Amm2&unique=prints",
                 "scryfall_set_uri": "https://scryfall.com/sets/mm2?utm_source=api",
                 "rulings_uri": "https://api.scryfall.com/cards/6b3a20ac-1860-4513-bb73-35d23b088b04/rulings",
                 "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ade2440de-e948-4811-903c-0bbe376ff64d&unique=prints",
                 "collector_number": "223",
                 "digital": False,
                 "rarity": "mythic",
                 "flavor_text": "The suns of Mirrodin have shone upon perfection only once.",
                 "illustration_id": "a88b0132-53ec-4d3e-b94e-7b160c821bfd",
                 "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
                 "artist": "Volkan Baǵa",
                 "border_color": "black",
                 "frame": "2015",
                 "full_art": False,
                 "textless": False,
                 "booster": True,
                 "story_spotlight": False,
                 "edhrec_rank": 756,
                 "prices": {"usd": "91.44",
                 "usd_foil": "114.35",
                 "eur": "70.51",
                 "tix": "39.21"},
                 "related_uris": {"gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=397719",
                 "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Mox+Opal&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall",
                 "edhrec": "http://edhrec.com/route/?cc=Mox+Opal",
                 "mtgtop8": "https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Mox+Opal"},
                 "purchase_uris": {"tcgplayer": "https://shop.tcgplayer.com/product/productsearch?id=98395&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall",
                 "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Modern-Masters-2015/Mox-Opal?referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
                 "cardhoarder": "https://www.cardhoarder.com/cards/57258?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"}}

GOOD_RESPONSE_SETS = ['Judge Gift Cards 2019',
                      'Kaladesh Inventions',
                      'Modern Masters 2015',
                      'Scars of Mirrodin']

GOOD_PAYLOAD = {'name': 'Mox Opal',
                'expansion': 'Scars of Mirrodin',
                'condition': 'NM',
                'foil': False,
                'quantity': 4}


BAD_RESPONSE = {
    "non_field_errors": [
        "There is no such card Mx Pl in Scars of Mirrodin set"
    ]
}