# Generated by Django 2.2 on 2019-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0003_auto_20190422_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='unit_value',
        ),
        migrations.AddField(
            model_name='cards',
            name='foil',
            field=models.BooleanField(default=False, verbose_name='Foil'),
        ),
        migrations.AddField(
            model_name='cards',
            name='set',
            field=models.CharField(blank=True, max_length=64, verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Value quantity value'),
        ),
    ]
